version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: document/requirements.txt

mkdocs:
  configuration: document/mkdocs.yml
  fail_on_warning: false
