[tool.poetry]
name = "graia-ariadne-dev"
version = "2021.12.13.2"
description = "Another elegant framework for mirai and mirai-api-http v2."
authors = [
    "BlueGlassBlock <blueglassblock@outlook.com>",
    "GreyElaina <GreyElaina@outlook.com>"
]
packages = [{ include = "graia", from = "src" }]
readme = "README.md"
repository = "https://github.com/GraiaProject/Ariadne"
homepage = "https://graia.readthedocs.io/zh_CN/latest"

[[tool.poetry.source]]
name = "tuna-tsinghua"
default = false
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"

[tool.poetry.dependencies]
python = "^3.8"
graia-broadcast = ">=0.14.4"
aiohttp = "^3.7.4"
pydantic = "^1.8.2"
yarl = "^1.6.3"
loguru = "^0.5.3"
typing-extensions = "^3.10.0"
prompt-toolkit = "^3.0.24"

[tool.poetry.dev-dependencies]
black = ">=21.10b0"
isort = ">=5.9.3"
devtools = ">=0.8.0"
objgraph = ">=3.5.0"
ptpython = ">=3.0.20"
graia-saya = "^0.0.13"
mkdocs-material = ">=7.3.6"
graia-scheduler = "^0.0.6"
pydeps = "^1.10.12"
pre-commit = "^2.16.0"
pdoc = "^8.0.1"
requests = { version = "^2.26.0", extras = ["dev"] }
pytest = "^6.2.5"
coverage = "^6.2"

[tool.isort]
profile = "black"

[tool.black]
line-length = 110
target-version = ['py39']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
branch = true
omit = ["*/test/*"]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    # standard pragma
    "pragma: no cover",
    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",
    "if .*TYPE_CHECKING:",
    "\\.\\.\\.",
    "pass",
    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
]
