[tool.poetry]
name = "graia-ariadne-dev"
version = "2021.12.15.2"
description = "Another elegant framework for mirai and mirai-api-http v2."
authors = [
    "BlueGlassBlock <blueglassblock@outlook.com>",
    "GreyElaina <GreyElaina@outlook.com>"
]
packages = [{ include = "graia", from = "src" }]
readme = "README.md"
repository = "https://github.com/GraiaProject/Ariadne"
homepage = "https://graia.readthedocs.io/zh_CN/latest"

[[tool.poetry.source]]
name = "tuna-tsinghua"
default = false
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"

[tool.poetry.dependencies]
python = "^3.8"
graia-broadcast = ">=0.14.4"
aiohttp = "^3.7.4"
pydantic = "^1.8.2"
yarl = "^1.7"
loguru = "^0.5"
typing-extensions = "^3.10.0"
prompt-toolkit = "^3.0.24"
arclet-alconna = { version = "^0.1.3", optional = true }
graia-scheduler = { version = "^0.0.6", optional = true }
graia-saya = { version = "^0.0.13", optional = true }

[tool.poetry.extras]
alconna = ["arclet-alconna"]
full = ["graia-saya", "graia-scheduler"]
dev = [
    "devtools",
    "objgraph",
    "ptpython",
    "pydeps",
    "pre-commit",
    "requests",
    "black",
    "isort"
]
qc = ["pytest", "coverage", "flake8"]

[tool.poetry.dev-dependencies]
black = { version = ">=21.10b0", optional = true }
isort = { version = ">=5.9.3", optional = true }
mkdocs-material = ">=7.3.6"
pdoc = "^8.0"
devtools = { version = ">= 0.8", optional = true }
objgraph = { version = ">= 3.5", optional = true }
ptpython = { version = ">= 3.0", optional = true }
pydeps = { version = "^1.10", optional = true }
pre-commit = { version = "^2.16", optional = true }
requests = { version = "^2.26", optional = true }
pytest = { version = "^6.2", optional = true }
coverage = { version = "^6.2", optional = true }
flake8 = { version = "^4.0", optional = true }

[tool.isort]
profile = "black"

[tool.black]
line-length = 110
target-version = ['py39']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
branch = true
omit = ["*/test/*"]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    # standard pragma
    "pragma: no cover",
    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",
    "if (typing\\.)?TYPE_CHECKING( is True)?:",
    "\\.\\.\\.",
    "pass",
    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
    # Don't complain overload method / functions
    "@(typing\\.)?overload"
]
