name: Build and deploy API Docs
on:
  push:
    branches:
      - master
      - dev
jobs:
  prepare-env:
    uses: GraiaProject/Ariadne/.github/workflows/mk-env.yml@dev
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Generate with pdoc
        run: |
          poetry run pdoc --docformat google ./src/graia/ariadne --footer-text "© Graia Project 2021" -e "ariadne=https://github.com/GraiaProject/Ariadne/blob/master/src/graia/ariadne/" -o ./api-doc

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: api-doc
