name: Build and deploy API Docs
on:
  push:
    branches:
      - master
      - dev
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.9

            - name: Setup Poetry
              uses: abatilo/actions-poetry@v2.0.0
              with:
                poetry-version: 1.1.11

            - name: Setup Poetry Dependencies
              run: |
                poetry install

            - name: Generate with pdoc
              run: |
                poetry run pdoc --docformat google ./src/graia/ariadne --footer-text "© Graia Project 2021" -e "ariadne=https://github.com/GraiaProject/Ariadne/blob/master/src/graia/ariadne/" -o ./api-doc

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@4.1.7
              with:
                  branch: gh-pages
                  folder: api-doc
