name: Publish to PyPI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: prepare-env
        uses: GraiaProject/Ariadne/.github/workflows/mk-env.yml@dev

      - name: Poetry build
        run: |
          poetry build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: dist/

      - name: Poetry Publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
