name: Python Publish
on:
  workflow_dispatch:

jobs:
  prepare-env:
    uses: GraiaProject/Ariadne/.github/workflows/mk-env.yml@dev

  build:
    runs-on: ubuntu-latest
    needs: prepare-env
    steps:
      - name: Poetry build
        run: |
          poetry build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: dist/

      - name: Poetry Publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
